### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [phodal/iot#13]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine doc/ppt/js/impress.js and observe `transtion`, however expect to see `transition`.
- Examine doc/ppt/jmpress.js-master/src/plugins/presentation-mode.js and observe `orgins`, however expect to see `origins`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR.

https://github.com/timgates42/iot/pull/new/bugfix_typos

Thanks.

**Comment by phodal** [comment]
thanks, just try it

**Comment by timgates42** [comment]
Thanks @phodal have opened the PR #14
